AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  latest-tweet obtains your latest tweet and stores it!

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        CONSUMER_KEY: VALUE
        CONSUMER_SECRET: VALUE
        ACCESS_KEY: VALUE
        ACCESS_SECRET: VALUE
        TABLE_NAME: VALUE
  Api:
    EndpointConfiguration: REGIONAL
    Cors: "'*'" # Local Development friendly. Replace with your domain.

Resources:
  GetTweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-tweet
      Handler: get-tweet
      Runtime: go1.x
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LatestTweetTable
      Events:
        HttpGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tweet
            Method: GET
  WatchForLatestTweetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: watch-for-latest-tweet
      Handler: watch-for-latest-tweet
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LatestTweetTable
      Events:
        CheckForLatestTweet:
          Type: Schedule
          Properties:
            Schedule: rate(20 minutes)
            Name: check-for-latest-tweet
            Description: Pings twitter for latest tweet and updates record in Dynamo when tweet differs
            Enabled: True
  LatestTweetTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: latest-tweet-table
      PrimaryKey:
        Name: ID
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        Department: Engineering
        AppType: Serverless
      SSESpecification:
        SSEEnabled: true
# Outputs:
# # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# # Find out more about other implicit resources you can reference within SAM
# # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# GetTweetAPI:
#   Description: "API Gateway endpoint URL for Prod environment for First Function"
#   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/watch-for-latest-tweet/"
# GetTweetFunction:
#   Description: "ARN of GetTweet Function"
#   Value: !GetAtt GetTweetFunction.Arn
# GetTweetFunctionIamRole:
#   Description: "Implicit IAM Role created for Get Tweet function"
#   Value:
#     !GetAtt GetTweetFunctionRole.Arn
# Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
# Properties:
#   Path: /tweet
#   Method: GET
